### ISSUE TITLE
Error message on startup

### ISSUE THREAD

**Issue by bkpeterson** [bitfocus/companion-module-bmd-hyperdeck#51]
I am using Companion 2.1.3 and have connections to 2 BlackMagic HyperDeck Studio Mini devices.  Since upgrading to 2.1.3 (from 2.1.2) I now get this error every single time on startup (I use a batch script to startup Companion - as a result the terminal window stays open).  It took a while to trace it, but this is an error returned by the HyperDeck.  I can't tell if this is coming from the module code or the hyperdeck-connection library.  It doesn't seem to affect function, but it is an error nonetheless....

This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handledd with .catch(). The promise rejected with the reason: { code: 107, name: 'timeline empty', params: {} }

**Comment by sphlabs** [comment]
Thanks for the bug report. This was due to an uncaught failure response when there are no clips on the current timeline.

A temporary fix has been added that, for now, generates a log error rather than the console error. Some additional support in hyperdeck-connection will be required to fully fix the issue.

**Comment by sphlabs** [comment]
This should be fixed in the latest release now.
