### ISSUE TITLE
Action triggers from end if clip playback

### ISSUE THREAD

**Issue by pscphil** [bitfocus/companion-module-bmd-hyperdeck#53]
I am trying to create an action that will let a whole single clip play and end on a camera once the clip has played. Do I have to set the Ms to the duration of the clip or should it be able to cut at the end of the clip?

**Comment by AndyHuska** [comment]
(Copied this from one of my recent Slack posts)

I’ve modified my fork of bmd-hyperdeck to allow the storing of timecode variables (in this case just two specific ones, for now, In Point and Out Point).  I’ve also added the ability for the module to programmatically press a button when the timecode hits the Out Point.  My usage is to mark In and Out, be able jump to them quickly to verify, then start playback with a button action that also arms a button press (user selectable in the action) at Out to tell my ATEM to crossfade to a different input (since it can push any button you can have anything happen).  It also does timecode math to store the segment duration as a variable for use, such as sending that time to ProPresenter for a countdown timer.

I imagine this could be made more generic as a timecode trigger.  I thought about using the global triggers and storing state variables, but it seemed to spread logic across too many places and possibly introduce some race conditions.

**Comment by sphlabs** [comment]
I believe it is now possible to achieve what you describe with the current module.

You can use the status of a hyperdeck as part of a trigger (playing, stopped, etc). Combined with custom variables, you could create an action that triggers when it is 'armed' (with a custom variable) and when the status changes to stopped. You could even add a condition for a specific clip by name, with the clipName variable.
