### ISSUE TITLE
Variables used in action - EX. Black Magic - Hyperdeck -Record (with name)

### ISSUE THREAD

**Issue by jhull88** [bitfocus/companion-module-bmd-hyperdeck#61]
Hi Team, 

Would love to allow variables to be used within an action. Example: 

If using a Black Magic Hyperdeck, you can create an action 'Record (with name)'. This allows the hyperdeck to record video files with a custom name. ex. "myvideoprojectname_0001" every time record is pressed. We have many hyperdecks on the same server. We would like to be able to create a filenameing prefix using a variable ex. "variable_hyperdeck01_0001" or "hyperdeck01_variable_0001"

This way, when we record across all our hyperdecks all the file names will have the same prefix. 

Here is an image of what did not work.
![image](https://user-images.githubusercontent.com/61551861/149200264-38d9783e-1600-4c6e-9322-b93da6c5e460.png)

Currently if you try to put a variable in the "Filename (without extension)" field, it will ignore the variable, and write on the memory card whatever is in that field.

Maybe I'm missing some syntax? 

Thanks, 

-JH

**Comment by jhull88** [comment]
Thanks! Would love to see this implemented for this module.

**Comment by thumperdisney** [comment]
+1 for this request.  It is very important for my case use as well.  I have 9 HyperDeck mini units with the record command all tied together that are used to record 9 different cameras for each race in a performance of 10-20 races and a variable would allow me to have a $raceNum variable with one button to increase race#, another to decrease race# and a 3rd button to record with a filename of Race# $raceNum DVR# $dvrNum so when I ftp all the clips to one folder in a NAS storage unit at the end of the performance all the footage is organized. Obviously this means I want the ability to use plain text and variables in the name field at the same time so some type of character break syntax might be needed.  As it is now, I have to have 20+ record buttons for each of the 9 HypderDecks to name the files correctly and then another 20+ buttons to trigger the button for each recorder in order to do the same thing.
