### ISSUE TITLE
Select Video Input (SDI/HDMI) not working

### ISSUE THREAD

**Issue by sshunk** [bitfocus/companion-module-bmd-hyperdeck#83]
My Setup:
Raspberry Pi 4b running Ubuntu 22.04.1 LTS
Companion v2.4.1 installed with HyperDeck Module version 1.3.3
BMD Hyperdeck Studio HD Plus (v8.2)
Elgato StreamDeck

It does not matter if I use the StreamDeck or Web Buttons to call the Video Input to change on the HyperDeck.  Nothing happens.
I setup a StreamDeck button to change the input on the Hyperdeck.  Companion says Hyperdeck Studio HD Plus Input source: HDMI or SDI.
However, when I press the StreamDeck button, nothing happens.  I am assuming this is either a bug or I am doing something wrong with my setup.
Everything is on the same IP Subnet.  It is pingable and other buttons work just fine.
On the Hyperdeck I either playback footage from SD Card or use the HDMI In/Out.  I want to be able to switch between Playback and HDMI In/Out with a push of a button or using a Macro so I don't have to physically walk over to my rack and press the Input button.

When I created my HyperDeck Video Input change button I did the following.
Went to the **Button** Tab > Selected a **blank button** > Selected **Presets** > Selected **HyperDeck Studio HD Plus** > Selected "**HD-StudioHDPlus: Video Input**" > Selected from drop drown menu **HDMI**

What else can I provide you to help resolve this issue?

**Comment by sphlabs** [comment]
To check my understanding of your issue:
- You play a clip from an SD card
- You Press the button with the **Video Input: HDMI** action
- Nothing happens

Hyperdecks have several state that they can be in (Play, Stopped, Record, etc). Only two of those state will show you the incoming signal -- Record and Preview. Changing/selecting the video input source does not change the transport status.

So, if you have just played a clip, the deck will be in **Stop** mode. In order to see the input signal you need to change to either **Record** or **Preview**.

If I have understood correctly they if you add an action to your HDMI button to set the **Transport status
: Preview** then that button will select HDMI as the input and put the deck into Preview mode, ready to record.

Hopefully that helps, let me know if there is a different problem.

**Comment by sshunk** [comment]
Thank you, Stephen.

Your thinking is correct.

I will check this very thing out and run some tests.
Is this information about "states" located in the user manual?  I was not aware only two of them would trigger the input.

I will get back to you by this weekend if the proposed solution worked.

Stephen Shunk
________________________________

**Comment by sphlabs** [comment]
You are still selecting the active input, regardless of transport status. But if you have been playing clips (and in Output mode) the deck will not switch to displaying an incoming signal (Preview mode) without being explicitly told to--either with a Preview command or by starting to record.

**Comment by sshunk** [comment]
Thank you Stephen,

Your insight helped solve my issue.

On my Companion I added an extra action to my button.
1. Set to Preview State
2. Change source input.

Solved.

I'll go ahead and make this issue resolved.

Stephen Shunk
________________________________
